// Generated by colorlab.dev
// https://colorlab.dev/WyIxLjAuMCIsIiMyYTYyOGYiLDExLDAsMCwiaHNsdXYiLCJsaW5lYXIiXQ==
//
// Base: #2a628f
// Stops: 11
// Easing: linear
// Mode: hsluv
// Hue-shift: 0, 0

const blue = {
  "0": {
    hex: "#fbfcff",
    css: "rgb(251,252,255)",
    hsl: "hsl(225,100%,99.22%)",
    rgb: {
      r: 251,
      g: 252,
      b: 255,
    },
  },
  "10": {
    hex: "#d5e4fa",
    css: "rgb(213,228,250)",
    hsl: "hsl(215.68,78.72%,90.78%)",
    rgb: {
      r: 213,
      g: 228,
      b: 250,
    },
  },
  "20": {
    hex: "#abcdf6",
    css: "rgb(171,205,246)",
    hsl: "hsl(212.8,80.65%,81.76%)",
    rgb: {
      r: 171,
      g: 205,
      b: 246,
    },
  },
  "30": {
    hex: "#7cb7f2",
    css: "rgb(124,183,242)",
    hsl: "hsl(210,81.94%,71.76%)",
    rgb: {
      r: 124,
      g: 183,
      b: 242,
    },
  },
  "40": {
    hex: "#49a0e7",
    css: "rgb(73,160,231)",
    hsl: "hsl(206.96,76.7%,59.61%)",
    rgb: {
      r: 73,
      g: 160,
      b: 231,
    },
  },
  "50": {
    hex: "#3d89c5",
    css: "rgb(61,137,197)",
    hsl: "hsl(206.47,53.97%,50.59%)",
    rgb: {
      r: 61,
      g: 137,
      b: 197,
    },
  },
  "60": {
    hex: "#3272a5",
    css: "rgb(50,114,165)",
    hsl: "hsl(206.61,53.49%,42.16%)",
    rgb: {
      r: 50,
      g: 114,
      b: 165,
    },
  },
  "70": {
    hex: "#2a628f",
    css: "rgb(42,98,143)",
    hsl: "hsl(206.73,54.59%,36.27%)",
    rgb: {
      r: 42,
      g: 98,
      b: 143,
    },
  },
  "80": {
    hex: "#1c4668",
    css: "rgb(28,70,104)",
    hsl: "hsl(206.84,57.58%,25.88%)",
    rgb: {
      r: 28,
      g: 70,
      b: 104,
    },
  },
  "90": {
    hex: "#12324b",
    css: "rgb(18,50,75)",
    hsl: "hsl(206.32,61.29%,18.24%)",
    rgb: {
      r: 18,
      g: 50,
      b: 75,
    },
  },
  "100": {
    hex: "#081f31",
    css: "rgb(8,31,49)",
    hsl: "hsl(206.34,71.93%,11.18%)",
    rgb: {
      r: 8,
      g: 31,
      b: 49,
    },
  },
  stops: 11,
  default: {
    hex: "#2a628f",
    css: "rgb(42,98,143)",
    hsl: "hsl(206.73,54.59%,36.27%)",
    rgb: {
      r: 42,
      g: 98,
      b: 143,
    },
  },
  defaultStop: 70,
};

export default blue;
