// Generated by colorlab.dev
// https://colorlab.dev/WyIxLjAuMCIsIiM0YWJkYWMiLDExLDAsMCwiaHNsdXYiLCJsaW5lYXIiXQ==
//
// Base: #4abdac
// Stops: 11
// Easing: linear
// Mode: hsluv
// Hue-shift: 0, 0

const green = {
  "0": {
    hex: "#f4fffc",
    css: "rgb(244,255,252)",
    hsl: "hsl(163.64,100%,97.84%)",
    rgb: {
      r: 244,
      g: 255,
      b: 252,
    },
  },
  "10": {
    hex: "#64fae4",
    css: "rgb(100,250,228)",
    hsl: "hsl(171.2,93.75%,68.63%)",
    rgb: {
      r: 100,
      g: 250,
      b: 228,
    },
  },
  "20": {
    hex: "#59dfcb",
    css: "rgb(89,223,203)",
    hsl: "hsl(171.04,67.68%,61.18%)",
    rgb: {
      r: 89,
      g: 223,
      b: 203,
    },
  },
  "30": {
    hex: "#4abdac",
    css: "rgb(74,189,172)",
    hsl: "hsl(171.13,46.56%,51.57%)",
    rgb: {
      r: 74,
      g: 189,
      b: 172,
    },
  },
  "40": {
    hex: "#42ab9b",
    css: "rgb(66,171,155)",
    hsl: "hsl(170.86,44.3%,46.47%)",
    rgb: {
      r: 66,
      g: 171,
      b: 155,
    },
  },
  "50": {
    hex: "#379184",
    css: "rgb(55,145,132)",
    hsl: "hsl(171.33,45%,39.22%)",
    rgb: {
      r: 55,
      g: 145,
      b: 132,
    },
  },
  "60": {
    hex: "#2d796e",
    css: "rgb(45,121,110)",
    hsl: "hsl(171.32,45.78%,32.55%)",
    rgb: {
      r: 45,
      g: 121,
      b: 110,
    },
  },
  "70": {
    hex: "#226158",
    css: "rgb(34,97,88)",
    hsl: "hsl(171.43,48.09%,25.69%)",
    rgb: {
      r: 34,
      g: 97,
      b: 88,
    },
  },
  "80": {
    hex: "#194b43",
    css: "rgb(25,75,67)",
    hsl: "hsl(170.4,50%,19.61%)",
    rgb: {
      r: 25,
      g: 75,
      b: 67,
    },
  },
  "90": {
    hex: "#0f3530",
    css: "rgb(15,53,48)",
    hsl: "hsl(172.11,55.88%,13.33%)",
    rgb: {
      r: 15,
      g: 53,
      b: 48,
    },
  },
  "100": {
    hex: "#07211d",
    css: "rgb(7,33,29)",
    hsl: "hsl(170.77,65%,7.84%)",
    rgb: {
      r: 7,
      g: 33,
      b: 29,
    },
  },
  stops: 11,
  default: {
    hex: "#4abdac",
    css: "rgb(74,189,172)",
    hsl: "hsl(171.13,46.56%,51.57%)",
    rgb: {
      r: 74,
      g: 189,
      b: 172,
    },
  },
  defaultStop: 30,
};

export default green;
