name: Test and build

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "!master"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

    steps:
      - uses: actions/checkout@v2

      - name: Install Deps
        run: npm install

      - name: Migrate DB
        run: npm run migrate
        env:
          DATABASE_CONNECTION_URL: postgresql://postgres:postgres@localhost:5432

      - name: Test
        run: npm run test
        env:
          DATABASE_CONNECTION_URL: postgresql://postgres:postgres@localhost:5432

      - name: Build
        run: npm run build
