name: Test and build

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "!master"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

    steps:
      - uses: actions/checkout@v2

      - name: Setup database
        run: psql -c "create database maine_go_ladder_test"

      - name: Install and test
        run: |
          npm install
          npm run test
          npm run build
